using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.IO;
using System.Diagnostics;

namespace WindowsFormsApplication1
{
    public partial class Form1 : Form
    {
        private System.Windows.Forms.OpenFileDialog openFileDialog1;  
       // this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileName = fileName + "DBC_TO_Header\\ConsoleApplication\\Release\\ConsoleApplication1.exe";
            Process.Start(fileName);
        }

        private void button3_Click(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string  fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Database.txt";

            OpenFileDialog openFileDialog1 = new OpenFileDialog
            {
                InitialDirectory = @"D:\",
                Title = "Browse Text Files",

                CheckFileExists = true,
                CheckPathExists = true,

                DefaultExt = "txt",
                Filter = "txt files (*.dbc)|*.dbc",
                FilterIndex = 2,
                RestoreDirectory = true,

                ReadOnlyChecked = true,
                ShowReadOnly = true
            };

            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                Location = openFileDialog1.FileName;
                File.WriteAllText(fileNameRelase, Location);
                textBox2.Text = openFileDialog1.FileName;
            }
            
        }

        private void button4_Click(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Resource.txt";

            var saveFileDialog1 = new SaveFileDialog
            {
                InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Personal),
                Filter = string.Format("{0}Text files (*.txt)|*.txt|All files (*.*)|*.*", "ARG0"),
                RestoreDirectory = true,
                ShowHelp = true,
                CheckFileExists = false
            };
            if (saveFileDialog1.ShowDialog() == DialogResult.OK)
            {
                Location = saveFileDialog1.FileName;
                File.WriteAllText(fileNameRelase, Location);
                textBox3.Text = Location;
            }
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {

        }

        private void textBox3_TextChanged(object sender, EventArgs e)
        {

        }

        private void button5_Click(object sender, EventArgs e)
        {
            MessageBox.Show(this, "*\n* Thie software create to generate hedar files and source file\n* for software developers.\n* The propose was to reduce software mistakes to non.\n* Software generated by Validation team.\n* Autor:Hamid Bakhtiary Davijany.\n* www.sazehpouesh.com\n* All rights reserved.\n*", "About", MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            
            switch (MessageBox.Show(this, "Are you sure?", "Do you still want ... ?", MessageBoxButtons.YesNo, MessageBoxIcon.Question))
            {
                //Stay on this form
                case DialogResult.No:
                    e.Cancel = true;
                    break;
                default:           
                    string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
                    string fileName = Path.Combine(path);
                    string fileNameRelase;
                    fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
                    fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Database.txt";
                    File.WriteAllText(fileNameRelase, "");
                    fileNameRelase = fileNameRelase.Replace("Database.txt","Resource.txt");
                    File.WriteAllText(fileNameRelase, "");
                    fileNameRelase = fileNameRelase.Replace("Resource.txt", "Node1.txt");
                    File.WriteAllText(fileNameRelase, "");
                    fileNameRelase = fileNameRelase.Replace("Node1.txt", "Node2.txt");
                    File.WriteAllText(fileNameRelase, "");
                    fileNameRelase = fileNameRelase.Replace("Node2.txt", "Node3.txt");
                    File.WriteAllText(fileNameRelase, "");
                    fileNameRelase = fileNameRelase.Replace("Node4.txt", "Node5.txt");
                    File.WriteAllText(fileNameRelase, "");
                    break;
            }
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Node1.txt";

            Location = comboBox1.Text;
            File.WriteAllText(fileNameRelase, Location);
        }

        private void comboBox2_SelectedIndexChanged(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Node2.txt";

            Location = comboBox2.Text;
            File.WriteAllText(fileNameRelase, Location);
        }

        private void comboBox3_SelectedIndexChanged(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Node3.txt";

            Location = comboBox3.Text;
            File.WriteAllText(fileNameRelase, Location);
        }

        private void comboBox4_SelectedIndexChanged(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Node4.txt";

            Location = comboBox4.Text;
            File.WriteAllText(fileNameRelase, Location);
        }

        private void comboBox5_SelectedIndexChanged(object sender, EventArgs e)
        {
            string Location;
            string path = System.Reflection.Assembly.GetExecutingAssembly().Location;
            string fileName = Path.Combine(path);
            string fileNameRelase;

            fileName = fileName.Replace("WindowsFormsApplication1\\bin\\Release\\WindowsFormsApplication1.exe", "");
            fileNameRelase = fileName + "WindowsFormsApplication1\\bin\\Release\\Node5.txt";

            Location = comboBox5.Text;
            File.WriteAllText(fileNameRelase, Location);
        }

    }
}